# Car Price Prediction::

Download dataset from this link:

https://www.kaggle.com/hellbuoy/car-price-prediction

# Problem Statement::

A Chinese automobile company Geely Auto aspires to enter the US market by setting up their manufacturing unit there and producing cars locally to give competition to their US and European counterparts.

They have contracted an automobile consulting company to understand the factors on which the pricing of cars depends. Specifically, they want to understand the factors affecting the pricing of cars in the American market, since those may be very different from the Chinese market. The company wants to know:

Which variables are significant in predicting the price of a car
How well those variables describe the price of a car
Based on various market surveys, the consulting firm has gathered a large data set of different types of cars across the America market.

# task::
We are required to model the price of cars with the available independent variables. It will be used by the management to understand how exactly the prices vary with the independent variables. They can accordingly manipulate the design of the cars, the business strategy etc. to meet certain price levels. Further, the model will be a good way for management to understand the pricing dynamics of a new market.

# WORKFLOW ::

1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

4.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

5.Compilation Step (Note : Its a Regression problem , select loss , metrics according to it)
6.Train the Model with Epochs (100) and validate it

7.If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .

8.Evaluation Step

9.Prediction

In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

from sklearn.compose import make_column_transformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [36]:
df = pd.read_csv("C:\\Users\\meesn\\workspace\\piaic 3rd assignment\\Car Price Prediction\\CarPrice_Assignment.csv")
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [37]:
df.shape

(205, 26)

In [38]:
df.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

**No Missing Values**

In [39]:
del df['car_ID']
del df['CarName']
df.head()

symboling fueltype aspiration doornumber      carbody drivewheel  \
0          3      gas        std        two  convertible        rwd   
1          3      gas        std        two  convertible        rwd   
2          1      gas        std        two    hatchback        rwd   
3          2      gas        std       four        sedan        fwd   
4          2      gas        std       four        sedan        4wd   

  enginelocation  wheelbase  carlength  carwidth  ...  enginesize  fuelsystem  \
0          front       88.6      168.8      64.1  ...         130        mpfi   
1          front       88.6      168.8      64.1  ...         130        mpfi   
2          front       94.5      171.2      65.5  ...         152        mpfi   
3          front       99.8      176.6      66.2  ...         109        mpfi   
4          front       99.4      176.6      66.4  ...         136        mpfi   

  boreratio stroke  compressionratio horsepower  peakrpm  citympg  highwaympg  \
0      3.47   2.68               9.0        111     5000       21          27   
1      3.47   2.68               9.0        111     5000       21          27   
2      2.68   3.47               9.0        154     5000       19          26   
3      3.19   3.40              10.0        102     5500       24          30   
4      3.19   3.40               8.0        115     5500       18          22   

     price  
0  13495.0  
1  16500.0  
2  16500.0  
3  13950.0  
4  17450.0  

[5 rows x 24 columns]

In [40]:
df.columns

Index(['symboling', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'wheelbase', 'carlength', 'carwidth',
       'carheight', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize',
       'fuelsystem', 'boreratio', 'stroke', 'compressionratio', 'horsepower',
       'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object')

### For Encoding Part

In [41]:
df.dtypes

symboling             int64
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [42]:
categotical_fet = [i for i in df.columns if df.dtypes[i]=='object']

In [43]:
categotical_fet

['fueltype',
 'aspiration',
 'doornumber',
 'carbody',
 'drivewheel',
 'enginelocation',
 'enginetype',
 'cylindernumber',
 'fuelsystem']

#### For Converting all of the columns that are 2 Category based:

In [44]:
#for fuel, the colum have 2 categories ['gas', 'diesel'], converting them into int
df['fueltype'].unique()
processed_df = df.copy()

processed_df.fueltype = df.fueltype.apply(lambda x: 1 if x == 'gas' else 0)
processed_df.fueltype.unique() 
#1 = gass, 0 = diesel

array([1, 0], dtype=int64)

In [45]:
#for fuel, the colum have 2 categories ['std', 'turbo'], converting them into int
df['aspiration'].unique()

processed_df.aspiration = processed_df.aspiration.apply(lambda x: 1 if x == 'std' else 0)
processed_df.aspiration.unique()
#1 = std, 0 = turbo

array([1, 0], dtype=int64)

In [46]:
#for fuel, the colum have 2 categories ['two', 'four'], converting them into int
df['doornumber'].unique()

processed_df.doornumber = processed_df.doornumber.apply(lambda x: 1 if x == 'four' else 0)
processed_df.doornumber.unique()
#1 = four, 0 = two

array([0, 1], dtype=int64)

In [47]:
#for fuel, the colum have 2 categories ['front', 'rear'], converting them into int
df['enginelocation'].unique()

processed_df.enginelocation = processed_df.enginelocation.apply(lambda x: 1 if x == 'front' else 0)
processed_df.enginelocation.unique()
#1 = front, 0 = rear

array([1, 0], dtype=int64)

In [48]:
#for enginetype, the colum have 7 categories ['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv']
#but, the OHC stand for "OverHead Cam", So, we here care about is whether or not the engine is 
#an OHC or not. 

processed_df.enginetype = processed_df.enginetype.apply(lambda x: 1 if 'ohc' in x else 0)
processed_df.enginetype.unique()
processed_df.enginetype.value_counts()
#1 = OHC, 0 = not OHC

1    189
0     16
Name: enginetype, dtype: int64

#### For converting the cylander string number to integer numbers

In [49]:
def text2int(textnum, numwords={}):
    if not numwords:
      units = [
        "zero", "one", "two", "three", "four", "five", "six", "seven", "eight",
        "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen",
        "sixteen", "seventeen", "eighteen", "nineteen",
      ]

      tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]

      scales = ["hundred", "thousand", "million", "billion", "trillion"]

      numwords["and"] = (1, 0)
      for idx, word in enumerate(units):    numwords[word] = (1, idx)
      for idx, word in enumerate(tens):     numwords[word] = (1, idx * 10)
      for idx, word in enumerate(scales):   numwords[word] = (10 ** (idx * 3 or 2), 0)

    current = result = 0
    for word in textnum.split():
        if word not in numwords:
          raise Exception("Illegal word: " + word)

        scale, increment = numwords[word]
        current = current * scale + increment
        if scale > 100:
            result += current
            current = 0

    return result + current

In [50]:
#for cylindernumber, converting the numbers ['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'] 
#to their equalivalent, in integers
processed_df['cylindernumber'].unique()

processed_df.cylindernumber = processed_df.cylindernumber.apply(lambda x: text2int(x) )
processed_df.cylindernumber.unique()

array([ 4,  6,  5,  3, 12,  2,  8], dtype=int64)

#### For One Hot Encoding based

In [51]:
#for carbody, the colum have 5 categories ['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop']
oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(processed_df[['carbody']])

#we have to do this other wise, column name will contains syntax like
#(etcName,), So this will give proper name to column like etcName
names = np.asarray(oe_style.categories_)[0]

#for adding the newly created one hot encoded columns and removing the un-nessary one

processed_df = processed_df.join(pd.DataFrame(oe_results.toarray(), columns=names))
processed_df.drop('carbody', inplace=True, axis=1) #no use now

In [52]:
#for drivewheel, the colum have 3 categories ['rwd', 'fwd', '4wd']
oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(processed_df[['drivewheel']])

#we have to do this other wise, column name will contains syntax like
#(etcName,), So this will give proper name to column like etcName
names = np.asarray(oe_style.categories_)[0,]

#for adding the newly created one hot encoded columns and removing the un-nessary one
processed_df = processed_df.join(pd.DataFrame(oe_results.toarray(), columns=names))
processed_df.drop('drivewheel', inplace=True, axis=1) #no use now

In [53]:
#for fuelsystem, the colum have 8 categories, ['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi']
oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(processed_df[['fuelsystem']])

#we have to do this other wise, column name will contains syntax like
#(etcName,), So this will give proper name to column like etcName
names = np.asarray(oe_style.categories_)[0,]

#for adding the newly created one hot encoded columns and removing the un-nessary one
processed_df = processed_df.join(pd.DataFrame(oe_results.toarray(), columns=names))
processed_df.drop('fuelsystem', inplace=True, axis=1) #no use now

In [54]:
processed_df.head()

symboling  fueltype  aspiration  doornumber  enginelocation  wheelbase  \
0          3         1           1           0               1       88.6   
1          3         1           1           0               1       88.6   
2          1         1           1           0               1       94.5   
3          2         1           1           1               1       99.8   
4          2         1           1           1               1       99.4   

   carlength  carwidth  carheight  curbweight  ...  fwd  rwd  1bbl  2bbl  \
0      168.8      64.1       48.8        2548  ...  0.0  1.0   0.0   0.0   
1      168.8      64.1       48.8        2548  ...  0.0  1.0   0.0   0.0   
2      171.2      65.5       52.4        2823  ...  0.0  1.0   0.0   0.0   
3      176.6      66.2       54.3        2337  ...  1.0  0.0   0.0   0.0   
4      176.6      66.4       54.3        2824  ...  0.0  0.0   0.0   0.0   

   4bbl  idi  mfi  mpfi  spdi  spfi  
0   0.0  0.0  0.0   1.0   0.0   0.0  
1   0.0  0.0  0.0   1.0   0.0   0.0  
2   0.0  0.0  0.0   1.0   0.0   0.0  
3   0.0  0.0  0.0   1.0   0.0   0.0  
4   0.0  0.0  0.0   1.0   0.0   0.0  

[5 rows x 37 columns]

### for Train-Test Split

In [55]:
y = processed_df['price']
processed_df.drop('price', inplace=True, axis=1)

X = processed_df.copy()

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
# X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.5, random_state=1)

In [57]:
X_train.shape

(164, 36)

### Neuro Network

In [58]:
model = Sequential()
model.add(Dense(36, activation='relu'))
model.add(Dense(72, activation='relu'))
model.add(Dense(36, activation='relu'))
model.add(Dense(18, activation='relu'))
model.add(Dense(1))

In [59]:
model.compile('Adam', loss='mse', metrics='mae')

In [60]:
model.fit(X_train, y_train, epochs=100, verbose=1)

Epoch 1/100
6/6 [==============================] - 1s 3ms/step - loss: 251114646.8571 - mae: 13641.1318
Epoch 2/100
6/6 [==============================] - 0s 2ms/step - loss: 240249465.1429 - mae: 13192.2687
Epoch 3/100
6/6 [==============================] - 0s 3ms/step - loss: 264019808.0000 - mae: 13639.9936
Epoch 4/100
6/6 [==============================] - 0s 2ms/step - loss: 216382665.1429 - mae: 12394.6674
Epoch 5/100
6/6 [==============================] - 0s 3ms/step - loss: 198438288.0000 - mae: 12010.3135
Epoch 6/100
6/6 [==============================] - 0s 2ms/step - loss: 195793220.5714 - mae: 11846.9466
Epoch 7/100
6/6 [==============================] - 0s 3ms/step - loss: 175600728.0000 - mae: 10597.2150
Epoch 8/100
6/6 [==============================] - 0s 3ms/step - loss: 161762934.8571 - mae: 9970.4125
Epoch 9/100
6/6 [==============================] - 0s 2ms/step - loss: 128797713.1429 - mae: 8315.5033
Epoch 10/100
6/6 [==============================] - 0s 2ms/step - 

#### For testing

In [61]:
print(X_test.shape, np.asarray(y_test.shape) )

(41, 36) [41]


In [62]:
index = 10
# X_test.head()
ans = model.predict( X_test[index-1:index] )
print( ans, np.asarray(y_test[index-1:index]) )

[[11272.241]] [10245.]
